name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.8"
          channel: "stable"
          cache: true
      - name: Build Android
        run: |
          flutter pub get
          flutter build apk --release
          flutter build appbundle --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Android APK
          path: ./build/app/outputs/flutter-apk/app-release.apk
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: Android AAB
          path: ./build/app/outputs/bundle/release/app-release.aab
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.8"
          channel: "stable"
          cache: true
      - name: Build iOS
        run: |
          flutter pub get
          flutter build ios --release --no-codesign
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: iOS
          path: ./build/ios/iphoneos/Runner.app
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.8"
          channel: "stable"
          cache: true
      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release
      - name: Upload Web
        uses: actions/upload-artifact@v3
        with:
          name: Web
          path: ./build/web
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.8"
          channel: "stable"
          cache: true
      - name: Build Windows
        run: |
          flutter pub get
          flutter build windows --release
      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: ./build/windows/x64/runner/Release
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.8"
          channel: "stable"
          cache: true
      - name: Install Dependencies
        # https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers_linux/setup.md
        run: |
          sudo apt-get update
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          sudo apt-get install libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      - name: Build Linux
        run: |
          flutter pub get
          flutter build linux --release
      - name: Upload Linux
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: ./build/linux/x64/release/bundle
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.8"
          channel: "stable"
          cache: true
      - name: Build macOS
        run: |
          flutter pub get
          flutter build macos --release
      - name: Upload macOS
        uses: actions/upload-artifact@v3
        with:
          name: macOS
          path: ./build/macos/Build/Products/Release
